name: Node.js CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare secrets
        env:
          SIMPLE_CONTAINER_CONFIG: ${{ secrets.SC_CONFIG }}
        run: |
          bash <(curl -Ls "https://dist.simple-container.com/sc.sh") --version
          sc secrets reveal --force

      - name: Read .env
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
        keys-case: bypass

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get current version from package.json
        run: echo "VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Check if tag exists
        run: |
          if git rev-parse ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi
      
      - name: Create Git tag
        if: env.TAG_EXISTS == 'false'
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Publish to npm
        if: env.TAG_EXISTS == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ steps.dotenv.outputs.NPM_TOKEN }}
